//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCourt
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTran
    {
        public int BillId { get; set; }
        public int BMId { get; set; }
        public int ItemNo { get; set; }
        public int Quantity { get; set; }
        public int Amount { get; set; }
    
        public virtual BillMaster BillMaster { get; set; }
        public virtual Item Item { get; set; }
    }
}
