//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCourt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodCourtEntities : DbContext
    {
        public FoodCourtEntities()
            : base("name=FoodCourtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillMaster> BillMasters { get; set; }
        public virtual DbSet<BillTran> BillTrans { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<ItemMaster> ItemMasters { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<StockTran> StockTrans { get; set; }
    }
}
